name: Shell Globbing
description: Creates a JSON array of files matching the specified pattern.
inputs:
  pattern:
    description: The pattern to one or more files that will be globbed.
    required: true
outputs:
  result:
    description: A JSON array of files matching the specified pattern.
    value: ${{ steps.run.outputs.result }}
runs:
  using: composite
  steps:
    - run: |
        shopt -s globstar extglob
        result="[]"
        for match in ${{ inputs.pattern }}; do
          if [ -z "$result" ]; then
            result="$match"
          else
            result="$result, $match"
          fi
        done
        result="[${result}]"
        echo "result=$result" >> $GITHUB_OUTPUT
      shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
